export const __esModule: boolean;
export function makeBusinessSocket(config: any): {
    logger: any;
    getOrderDetails: (orderId: any, tokenBase64: any) => Promise<{
        price: {
            total: number;
            currency: any;
        };
        products: any;
    }>;
    getCatalog: ({ jid, limit, cursor }: {
        jid: any;
        limit: any;
        cursor: any;
    }) => Promise<{
        products: any;
        nextPageCursor: any;
    }>;
    getCollections: (jid: any, limit?: number) => Promise<{
        collections: any;
    }>;
    productCreate: (create: any) => Promise<{
        id: any;
        imageUrls: {
            requested: any;
            original: any;
        };
        reviewStatus: {
            whatsapp: any;
        };
        availability: string;
        name: any;
        retailerId: any;
        url: any;
        description: any;
        price: number;
        currency: any;
        isHidden: boolean;
    }>;
    productDelete: (productIds: any) => Promise<{
        deleted: number;
    }>;
    productUpdate: (productId: any, update: any) => Promise<{
        id: any;
        imageUrls: {
            requested: any;
            original: any;
        };
        reviewStatus: {
            whatsapp: any;
        };
        availability: string;
        name: any;
        retailerId: any;
        url: any;
        description: any;
        price: number;
        currency: any;
        isHidden: boolean;
    }>;
    updateBusinessProfile: (args: any) => Promise<any>;
    updateBussinesProfile: (args: any) => Promise<any>;
    updateCoverPhoto: (photo: any) => Promise<any>;
    removeCoverPhoto: (id: any) => Promise<any>;
    sendMessageAck: ({ tag, attrs, content }: {
        tag: any;
        attrs: any;
        content: any;
    }, errorCode: any) => Promise<void>;
    sendRetryRequest: (node: any, forceIncludeKeys?: boolean) => Promise<void>;
    rejectCall: (callId: any, callFrom: any) => Promise<void>;
    offerCall: (toJid: any, isVideo?: boolean) => Promise<{
        callId: any;
        toJid: any;
        isVideo: boolean;
    }>;
    fetchMessageHistory: (count: any, oldestMsgKey: any, oldestMsgTimestamp: any) => Promise<any>;
    requestPlaceholderResend: (messageKey: any, msgData: any) => Promise<any>;
    getPrivacyTokens: (jids: any) => Promise<any>;
    assertSessions: (jids: any, force: any) => Promise<boolean>;
    relayMessage: (jid: any, message: any, { messageId: msgId, participant, additionalAttributes, useUserDevicesCache, useCachedGroupMetadata, statusJidList, additionalNodes }: {
        messageId: any;
        participant: any;
        additionalAttributes: any;
        useUserDevicesCache: any;
        useCachedGroupMetadata: any;
        statusJidList: any;
        additionalNodes: any;
    }) => Promise<any>;
    sendReceipt: (jid: any, participant: any, messageIds: any, type: any) => Promise<void>;
    sendReceipts: (keys: any, type: any) => Promise<void>;
    readMessages: (keys: any) => Promise<void>;
    refreshMediaConn: (forceGet?: boolean) => Promise<any>;
    waUploadToServer: any;
    fetchPrivacySettings: (force?: boolean) => Promise<any>;
    getUSyncDevices: (jids: any, useCache: any, ignoreZeroDevices: any, ignore: any) => Promise<any[]>;
    createParticipantNodes: (jids: any, message: any, extraAttrs: any) => Promise<{
        nodes: any[];
        shouldIncludeDeviceIdentity: boolean;
    }>;
    sendPeerDataOperationMessage: (pdoMessage: any) => Promise<any>;
    updateMemberLabel: (jid: any, memberLabel: any) => Promise<any>;
    messageRetryManager: import("../Utils/message-retry-manager").MessageRetryManager;
    profilePictureUrl: (jid: any) => Promise<any>;
    sendStatusMentions: (content: any, jids?: any[]) => Promise<any>;
    sendGroupStatus: (groupIdsOrContent?: any[], contentOrGroups?: {}, opts?: {}) => Promise<string[]>;
    sendAlbumMessage: (jid: any, medias: any, options?: {}) => Promise<any>;
    updateMediaMessage: (message: any) => Promise<any>;
    sendMessage: (jid: any, content: any, options?: {}) => Promise<any>;
    newsletterId: (url: any) => Promise<any>;
    subscribeNewsletterUpdates: (jid: any) => Promise<any>;
    newsletterReactionMode: (jid: any, mode: any) => Promise<void>;
    newsletterUpdateDescription: (jid: any, description: any) => Promise<void>;
    newsletterUpdateName: (jid: any, name: any) => Promise<void>;
    newsletterUpdatePicture: (jid: any, content: any) => Promise<void>;
    newsletterRemovePicture: (jid: any) => Promise<void>;
    newsletterUnfollow: (jid: any) => Promise<void>;
    newsletterFollow: (jid: any) => Promise<void>;
    newsletterUnmute: (jid: any) => Promise<void>;
    newsletterMute: (jid: any) => Promise<void>;
    newsletterCreate: (name: any, description: any, picture: any) => Promise<{
        id: any;
        state: any;
        creation_time: number;
        name: any;
        nameTime: number;
        description: any;
        descriptionTime: number;
        invite: any;
        handle: any;
        picture: any;
        preview: any;
        reaction_codes: any;
        subscribers: number;
        verification: any;
        viewer_metadata: any;
    }>;
    newsletterMetadata: (type: any, key: any, role: any) => Promise<{
        id: any;
        state: any;
        creation_time: number;
        name: any;
        nameTime: number;
        description: any;
        descriptionTime: number;
        invite: any;
        handle: any;
        picture: any;
        preview: any;
        reaction_codes: any;
        subscribers: number;
        verification: any;
        viewer_metadata: any;
    }>;
    newsletterAdminCount: (jid: any) => Promise<any>;
    newsletterSubscribers: (jid: any) => Promise<{
        subscribers: number;
    }>;
    newsletterChangeOwner: (jid: any, user: any) => Promise<void>;
    newsletterDemote: (jid: any, user: any) => Promise<void>;
    newsletterDelete: (jid: any) => Promise<void>;
    newsletterReactMessage: (jid: any, server_id: any, code: any) => Promise<void>;
    newsletterFetchMessages: (type: any, key: any, count: any, after: any) => Promise<any>;
    newsletterFetchUpdates: (jid: any, count: any, after: any, since: any) => Promise<any>;
    newsletterSubscribed: () => Promise<any>;
    groupQuery: (jid: any, type: any, content: any) => Promise<any>;
    groupMetadata: (jid: any) => Promise<{
        desc: any;
        descId: any;
        descOwner: any;
        descOwnerLid: any;
        descTime: number;
        linkedParent: any;
        restrict: boolean;
        announce: boolean;
        isCommunity: boolean;
        isCommunityAnnounce: boolean;
        joinApprovalMode: boolean;
        memberAddMode: boolean;
        participants: any;
        ephemeralDuration: number;
        ownerLid?: any;
        subjectTime: number;
        size: any;
        creation: number;
        owner: any;
        subjectOwnerLid?: any;
        id: any;
        addressingMode: any;
        subject: any;
        subjectOwner: any;
    }>;
    groupCreate: (subject: any, participants: any) => Promise<{
        desc: any;
        descId: any;
        descOwner: any;
        descOwnerLid: any;
        descTime: number;
        linkedParent: any;
        restrict: boolean;
        announce: boolean;
        isCommunity: boolean;
        isCommunityAnnounce: boolean;
        joinApprovalMode: boolean;
        memberAddMode: boolean;
        participants: any;
        ephemeralDuration: number;
        ownerLid?: any;
        subjectTime: number;
        size: any;
        creation: number;
        owner: any;
        subjectOwnerLid?: any;
        id: any;
        addressingMode: any;
        subject: any;
        subjectOwner: any;
    }>;
    groupLeave: (id: any) => Promise<void>;
    groupUpdateSubject: (jid: any, subject: any) => Promise<void>;
    groupRequestParticipantsList: (jid: any) => Promise<any>;
    groupRequestParticipantsUpdate: (jid: any, participants: any, action: any) => Promise<any>;
    groupParticipantsUpdate: (jid: any, participants: any, action: any) => Promise<any>;
    groupUpdateDescription: (jid: any, description: any) => Promise<void>;
    groupInviteCode: (jid: any) => Promise<any>;
    groupRevokeInvite: (jid: any) => Promise<any>;
    groupAcceptInvite: (code: any) => Promise<any>;
    groupRevokeInviteV4: (groupJid: any, invitedJid: any) => Promise<boolean>;
    groupAcceptInviteV4: any;
    groupGetInviteInfo: (code: any) => Promise<{
        desc: any;
        descId: any;
        descOwner: any;
        descOwnerLid: any;
        descTime: number;
        linkedParent: any;
        restrict: boolean;
        announce: boolean;
        isCommunity: boolean;
        isCommunityAnnounce: boolean;
        joinApprovalMode: boolean;
        memberAddMode: boolean;
        participants: any;
        ephemeralDuration: number;
        ownerLid?: any;
        subjectTime: number;
        size: any;
        creation: number;
        owner: any;
        subjectOwnerLid?: any;
        id: any;
        addressingMode: any;
        subject: any;
        subjectOwner: any;
    }>;
    groupToggleEphemeral: (jid: any, ephemeralExpiration: any) => Promise<void>;
    groupSettingUpdate: (jid: any, setting: any) => Promise<void>;
    groupMemberAddMode: (jid: any, mode: any) => Promise<void>;
    groupJoinApprovalMode: (jid: any, mode: any) => Promise<void>;
    groupFetchAllParticipating: () => Promise<{}>;
    createCallLink: (type: any, event: any, timeoutMs: any) => Promise<any>;
    getBotListV2: () => Promise<{
        jid: any;
        personaId: any;
    }[]>;
    processingMutex: {
        mutex(code: any): Promise<void>;
    };
    fetchProps: () => Promise<{}>;
    upsertMessage: any;
    appPatch: (patchCreate: any) => Promise<void>;
    sendPresenceUpdate: (type: any, toJid: any) => Promise<void>;
    presenceSubscribe: (toJid: any, tcToken: any) => Promise<void>;
    onWhatsApp: (...jids: any[]) => Promise<any>;
    fetchBlocklist: () => Promise<any>;
    fetchDisappearingDuration: (...jids: any[]) => Promise<any>;
    fetchStatus: (...jids: any[]) => Promise<any>;
    updateProfilePicture: (jid: any, content: any, dimensions: any) => Promise<void>;
    removeProfilePicture: (jid: any) => Promise<void>;
    updateProfileStatus: (status: any) => Promise<void>;
    updateProfileName: (name: any) => Promise<void>;
    updateBlockStatus: (jid: any, action: any) => Promise<void>;
    updateDisableLinkPreviewsPrivacy: (isPreviewsDisabled: any) => Promise<void>;
    updateCallPrivacy: (value: any) => Promise<void>;
    updateMessagesPrivacy: (value: any) => Promise<void>;
    updateLastSeenPrivacy: (value: any) => Promise<void>;
    updateOnlinePrivacy: (value: any) => Promise<void>;
    updateProfilePicturePrivacy: (value: any) => Promise<void>;
    updateStatusPrivacy: (value: any) => Promise<void>;
    updateReadReceiptsPrivacy: (value: any) => Promise<void>;
    updateGroupsAddPrivacy: (value: any) => Promise<void>;
    updateDefaultDisappearingMode: (duration: any) => Promise<void>;
    getBusinessProfile: (jid: any) => Promise<{
        wid: any;
        address: any;
        description: any;
        website: any[];
        email: any;
        category: any;
        business_hours: {
            timezone: any;
            business_config: any;
        };
    }>;
    resyncAppState: any;
    chatModify: (mod: any, jid: any) => Promise<void>;
    cleanDirtyBits: (type: any, fromTimestamp: any) => Promise<void>;
    addOrEditContact: (jid: any, contact: any) => Promise<void>;
    removeContact: (jid: any) => Promise<void>;
    addLabel: (jid: any, labels: any) => Promise<void>;
    addChatLabel: (jid: any, labelId: any) => Promise<void>;
    removeChatLabel: (jid: any, labelId: any) => Promise<void>;
    addMessageLabel: (jid: any, messageId: any, labelId: any) => Promise<void>;
    removeMessageLabel: (jid: any, messageId: any, labelId: any) => Promise<void>;
    addOrEditQuickReply: (quickReply: any) => Promise<void>;
    removeQuickReply: (timestamp: any) => Promise<void>;
    star: (jid: any, messages: any, star: any) => Promise<void>;
    findUserId: (jid: any) => Promise<{
        phoneNumber: any;
        lid: any;
    }>;
    executeUSyncQuery: (usyncQuery: any) => Promise<any>;
    type: string;
    ws: any;
    ev: any;
    authState: {
        creds: any;
        keys: any;
    };
    signalRepository: any;
    user: any;
    generateMessageTag: () => string;
    query: (node: any, timeoutMs: any) => Promise<any>;
    executeWMexQuery: (queryId: any, variables: any) => Promise<any>;
    fetchAccountReachoutTimelock: () => Promise<{
        isActive: boolean;
        timeEnforcementEnds: Date;
        enforcementType: any;
    }>;
    fetchNewChatMessageCap: () => Promise<any>;
    checkAccountRestriction: () => Promise<{
        isRestricted: boolean;
        reachoutTimelock: {
            isActive: boolean;
            timeEnforcementEnds: Date;
            enforcementType: any;
        };
        messageCap: any;
    }>;
    waitForMessage: (msgId: any, timeoutMs?: any) => Promise<any>;
    waitForSocketOpen: () => Promise<void>;
    sendRawMessage: (data: any) => Promise<void>;
    sendNode: (frame: any) => Promise<void>;
    logout: (msg: any) => Promise<void>;
    end: (error: any) => void;
    onUnexpectedError: (err: any, msg: any) => void;
    uploadPreKeys: (count?: 812) => Promise<void>;
    uploadPreKeysToServerIfRequired: () => Promise<void>;
    requestPairingCode: (phoneNumber: any, pairKey?: string) => Promise<any>;
    waitForConnectionUpdate: any;
    sendWAMBuffer: (wamBuffer: any) => Promise<any>;
};
