export const __esModule: boolean;
export const version: number[];
export const MAINTENANCE_MODE: false;
export const MAINTENANCE_MESSAGE: "[YEBAIL] Maintenance mode is currently active. Layanan sedang dalam perbaikan. Please try again later / Silakan coba kembali nanti.";
export const PHONENUMBER_MCC: {
    "93": number;
    "355": number;
    "213": number;
    "1-684": number;
    "376": number;
    "244": number;
    "1-264": number;
    "1-268": number;
    "54": number;
    "374": number;
    "297": number;
    "61": number;
    "43": number;
    "994": number;
    "1-242": number;
    "973": number;
    "880": number;
    "1-246": number;
    "375": number;
    "32": number;
    "501": number;
    "229": number;
    "1-441": number;
    "975": number;
    "591": number;
    "387": number;
    "267": number;
    "55": number;
    "1-284": number;
    "673": number;
    "359": number;
    "226": number;
    "257": number;
    "855": number;
    "237": number;
    "238": number;
    "1-345": number;
    "236": number;
    "235": number;
    "56": number;
    "86": number;
    "57": number;
    "269": number;
    "682": number;
    "506": number;
    "385": number;
    "53": number;
    "357": number;
    "420": number;
    "243": number;
    "45": number;
    "253": number;
    "1-767": number;
    "1-809": number;
    "1-849": number;
    "1-829": number;
    "593": number;
    "20": number;
    "503": number;
    "240": number;
    "291": number;
    "372": number;
    "251": number;
    "500": number;
    "298": number;
    "679": number;
    "358": number;
    "33": number;
    "689": number;
    "241": number;
    "220": number;
    "995": number;
    "49": number;
    "233": number;
    "350": number;
    "30": number;
    "299": number;
    "1-473": number;
    "1-671": number;
    "502": number;
    "224": number;
    "592": number;
    "509": number;
    "504": number;
    "852": number;
    "36": number;
    "354": number;
    "91": number;
    "62": number;
    "98": number;
    "964": number;
    "353": number;
    "972": number;
    "39": number;
    "225": number;
    "1-876": number;
    "81": number;
    "962": number;
    "254": number;
    "686": number;
    "383": number;
    "965": number;
    "371": number;
    "961": number;
    "266": number;
    "231": number;
    "218": number;
    "423": number;
    "370": number;
    "352": number;
    "389": number;
    "261": number;
    "265": number;
    "60": number;
    "960": number;
    "223": number;
    "356": number;
    "692": number;
    "222": number;
    "230": number;
    "52": number;
    "691": number;
    "373": number;
    "377": number;
    "976": number;
    "382": number;
    "1-664": number;
    "212": number;
    "258": number;
    "95": number;
    "264": number;
    "674": number;
    "977": number;
    "31": number;
    "687": number;
    "64": number;
    "505": number;
    "227": number;
    "234": number;
    "683": number;
    "1-670": number;
    "47": number;
    "968": number;
    "92": number;
    "680": number;
    "970": number;
    "507": number;
    "675": number;
    "595": number;
    "51": number;
    "63": number;
    "48": number;
    "351": number;
    "1-787, 1-939": number;
    "974": number;
    "242": number;
    "40": number;
    "7": number;
    "250": number;
    "290": number;
    "1-869": number;
    "1-758": number;
    "508": number;
    "1-784": number;
    "685": number;
    "378": number;
    "239": number;
    "966": number;
    "221": number;
    "381": number;
    "248": number;
    "232": number;
    "65": number;
    "386": number;
    "677": number;
    "27": number;
    "211": number;
    "34": number;
    "94": number;
    "249": number;
    "597": number;
    "268": number;
    "46": number;
    "41": number;
    "963": number;
    "886": number;
    "992": number;
    "255": number;
    "66": number;
    "228": number;
    "690": number;
    "676": number;
    "1-868": number;
    "216": number;
    "90": number;
    "993": number;
    "1-649": number;
    "688": number;
    "1-340": number;
    "256": number;
    "380": number;
    "971": number;
    "44": number;
    "1": number;
    "598": number;
    "998": number;
    "678": number;
    "379": number;
    "58": number;
    "681": number;
    "967": number;
    "260": number;
    "263": number;
    "670": number;
    "245": number;
    "856": number;
    "599": number;
    "850": number;
    "262": number;
    "82": number;
    "84": number;
};
export const UNAUTHORIZED_CODES: number[];
export const DEFAULT_ORIGIN: "https://web.whatsapp.com";
export const CALL_VIDEO_PREFIX: "https://call.whatsapp.com/video/";
export const CALL_AUDIO_PREFIX: "https://call.whatsapp.com/voice/";
export const DEF_CALLBACK_PREFIX: "CB:";
export const DEF_TAG_PREFIX: "TAG:";
export const PHONE_CONNECTION_CB: "CB:Pong";
export const WA_ADV_ACCOUNT_SIG_PREFIX: Buffer<ArrayBuffer>;
export const WA_ADV_DEVICE_SIG_PREFIX: Buffer<ArrayBuffer>;
export const WA_ADV_HOSTED_ACCOUNT_SIG_PREFIX: Buffer<ArrayBuffer>;
export const WA_ADV_HOSTED_DEVICE_SIG_PREFIX: Buffer<ArrayBuffer>;
export const WA_DEFAULT_EPHEMERAL: number;
export const NOISE_MODE: "Noise_XX_25519_AESGCM_SHA256\0\0\0\0";
export const DICT_VERSION: 3;
export const KEY_BUNDLE_TYPE: Buffer<ArrayBuffer>;
export const NOISE_WA_HEADER: Buffer<ArrayBuffer>;
export const URL_REGEX: RegExp;
export namespace WA_CERT_DETAILS {
    let SERIAL: number;
}
export const PROCESSABLE_HISTORY_TYPES: any[];
export namespace DEFAULT_CONNECTION_CONFIG {
    import version = version;
    export { version };
    export let browser: any[];
    export let waWebSocketUrl: string;
    export let connectTimeoutMs: number;
    export let keepAliveIntervalMs: number;
    export let logger: any;
    export let emitOwnEvents: boolean;
    export let defaultQueryTimeoutMs: number;
    export let customUploadHosts: any[];
    export let retryRequestDelayMs: number;
    export let maxMsgRetryCount: number;
    export let fireInitQueries: boolean;
    export let auth: any;
    export let markOnlineOnConnect: boolean;
    export let syncFullHistory: boolean;
    export function patchMessageBeforeSending(msg: any): any;
    export function shouldSyncHistoryMessage(): boolean;
    export function shouldIgnoreJid(): boolean;
    export let linkPreviewImageThumbnailWidth: number;
    export let albumMessageItemDelayMs: number;
    export namespace transactionOpts {
        let maxCommitRetries: number;
        let delayBetweenTriesMs: number;
    }
    export let generateHighQualityLinkPreview: boolean;
    export let enableAutoSessionRecreation: boolean;
    export let enableRecentMessageCache: boolean;
    export let options: {};
    export namespace appStateMacVerification {
        let patch: boolean;
        let snapshot: boolean;
    }
    export let countryCode: string;
    export let mcc: any;
    export function getMessage(): Promise<any>;
    export function cachedGroupMetadata(): Promise<any>;
    export let makeSignalRepository: typeof libsignal_1.makeLibSignalRepository;
}
export const MEDIA_PATH_MAP: {
    image: string;
    video: string;
    document: string;
    audio: string;
    sticker: string;
    'thumbnail-link': string;
    'product-catalog-image': string;
    'md-app-state': string;
    'md-msg-hist': string;
    'biz-cover-photo': string;
};
export const MEDIA_HKDF_KEY_MAPPING: {
    audio: string;
    document: string;
    gif: string;
    image: string;
    ppic: string;
    product: string;
    ptt: string;
    sticker: string;
    video: string;
    'thumbnail-document': string;
    'thumbnail-image': string;
    'thumbnail-video': string;
    'thumbnail-link': string;
    'md-msg-hist': string;
    'md-app-state': string;
    'product-catalog-image': string;
    'payment-bg-image': string;
    ptv: string;
    'biz-cover-photo': string;
};
export const MEDIA_KEYS: string[];
export const MIN_PREKEY_COUNT: 5;
export const INITIAL_PREKEY_COUNT: 812;
export const UPLOAD_TIMEOUT: 30000;
export const MIN_UPLOAD_INTERVAL: 5000;
export namespace DEFAULT_CACHE_TTLS {
    let SIGNAL_STORE: number;
    let MSG_RETRY: number;
    let CALL_OFFER: number;
    let USER_DEVICES: number;
}
export function getMccForCountryIso2(iso3166Alpha2: any): string;
declare namespace ___home_runner_work_baileys_baileys_lib_Defaults_index_ { }
import libsignal_1 = require("../Signal/libsignal");
export {};
