export const MENU_SECTIONS = [
  {
    title: '💬 Pesan',
    rows: [
      { title: '.ping', description: 'Cek apakah bot aktif', rowId: '.ping' },
      { title: '.menu', description: 'Tampilkan daftar perintah ini', rowId: '.menu' },
      { title: '.link', description: 'Kirim link dengan pratinjau', rowId: '.link' },
      { title: '.mention', description: 'Mention pengirim', rowId: '.mention' },
      { title: '.reply', description: 'Balas pesan dengan kutipan', rowId: '.reply' },
      { title: '.sticker', description: 'Kirim stiker', rowId: '.sticker' },
      { title: '.react', description: 'Kirim reaksi', rowId: '.react' },
      { title: '.unreact', description: 'Hapus reaksi', rowId: '.unreact' },
    ],
  },
  {
    title: '🖼️ Media',
    rows: [
      { title: '.image', description: 'Kirim gambar dari URL', rowId: '.image' },
      { title: '.video', description: 'Kirim video dari URL', rowId: '.video' },
      { title: '.gif', description: 'Kirim GIF', rowId: '.gif' },
      { title: '.audio', description: 'Kirim audio', rowId: '.audio' },
      { title: '.voice', description: 'Kirim pesan suara (PTT)', rowId: '.voice' },
      { title: '.ptv', description: 'Kirim video lingkaran (PTV)', rowId: '.ptv' },
      { title: '.doc', description: 'Kirim dokumen PDF', rowId: '.doc' },
      { title: '.viewonce', description: 'Kirim gambar sekali lihat', rowId: '.viewonce' },
      { title: '.album', description: 'Kirim album foto', rowId: '.album' },
      { title: '.download', description: 'Unduh media terakhir di chat', rowId: '.download' },
      { title: '.grayscale', description: 'Ubah gambar terakhir ke hitam putih', rowId: '.grayscale' },
      { title: '.resize', description: 'Resize gambar terakhir ke lebar 512px', rowId: '.resize' },
      { title: '.thumbnail', description: 'Buat thumbnail 200x200 dari gambar terakhir', rowId: '.thumbnail' },
    ],
  },
  {
    title: '📋 Interaktif',
    rows: [
      { title: '.list', description: 'Contoh pesan list', rowId: '.list' },
      { title: '.buttons', description: 'Contoh tombol (native flow)', rowId: '.buttons' },
      { title: '.interactive', description: 'Contoh native flow', rowId: '.interactive' },
      { title: '.quickreply', description: 'Contoh quick reply', rowId: '.quickreply' },
      { title: '.poll', description: 'Buat polling', rowId: '.poll' },
    ],
  },
  {
    title: '📌 Chat & Pesan',
    rows: [
      { title: '.edit', description: 'Edit pesan yang terkirim', rowId: '.edit' },
      { title: '.delete', description: 'Hapus pesan untuk semua', rowId: '.delete' },
      { title: '.pin', description: 'Sematkan pesan', rowId: '.pin' },
      { title: '.forward', description: 'Forward pesan terakhir', rowId: '.forward' },
      { title: '.markunread', description: 'Tandai chat belum dibaca', rowId: '.markunread' },
      { title: '.archive', description: 'Arsipkan chat', rowId: '.archive' },
      { title: '.mute', description: 'Bisukan chat 8 jam', rowId: '.mute' },
      { title: '.star', description: 'Bintangi pesan', rowId: '.star' },
    ],
  },
  {
    title: '👤 Profil & Privasi',
    rows: [
      { title: '.pfp', description: 'Ambil foto profil', rowId: '.pfp' },
      { title: '.exists', description: 'Cek nomor di WhatsApp', rowId: '.exists' },
      { title: '.status', description: 'Cek teks status', rowId: '.status' },
      { title: '.mystatus', description: 'Posting status dengan mention', rowId: '.mystatus' },
      { title: '.setname', description: 'Ubah nama profil bot', rowId: '.setname' },
      { title: '.setstatus', description: 'Ubah status profil bot', rowId: '.setstatus' },
      { title: '.privacy', description: 'Perbarui pengaturan privasi', rowId: '.privacy' },
      { title: '.disappear', description: 'Aktifkan pesan hilang 90 hari', rowId: '.disappear' },
    ],
  },
  {
    title: '🚫 Blokir',
    rows: [
      { title: '.blocklist', description: 'Lihat daftar blokir', rowId: '.blocklist' },
      { title: '.block', description: 'Blokir pengirim', rowId: '.block' },
      { title: '.unblock', description: 'Buka blokir pengirim', rowId: '.unblock' },
    ],
  },
  {
    title: '👥 Grup',
    rows: [
      { title: '.creategroup', description: 'Buat grup baru', rowId: '.creategroup' },
      { title: '.groups', description: 'Lihat semua grup', rowId: '.groups' },
      { title: '.invitelink <jid>', description: 'Dapatkan link undangan', rowId: '.invitelink' },
      { title: '.joingroup <kode>', description: 'Bergabung dengan kode', rowId: '.joingroup' },
      { title: '.groupinfo <jid>', description: 'Info grup', rowId: '.groupinfo' },
    ],
  },
  {
    title: '📰 Newsletter & Lainnya',
    rows: [
      { title: '.createnewsletter', description: 'Buat newsletter', rowId: '.createnewsletter' },
      { title: '.community', description: 'Buat komunitas', rowId: '.community' },
      { title: '.bots', description: 'Daftar bot WhatsApp', rowId: '.bots' },
      { title: '.calllink', description: 'Buat link panggilan video', rowId: '.calllink' },
      { title: '.typing', description: 'Simulasikan status mengetik', rowId: '.typing' },
      { title: '.pay', description: 'Kirim permintaan pembayaran', rowId: '.pay' },
      { title: '.contact', description: 'Kirim kartu kontak', rowId: '.contact' },
      { title: '.location', description: 'Kirim lokasi', rowId: '.location' },
    ],
  },
]
