name: Auto Update

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Update WhatsApp Web Version
        run: node scripts/update-wa-version.js

      - name: Update WAProto Files
        run: node scripts/update-wa-proto.js
        continue-on-error: true

      - name: Commit and Push changes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add lib/Defaults/yebail-version.json lib/Defaults/index.js WAProto scripts package.json

          if git diff --staged --quiet; then
            echo "No changes detected, skipping update."
            exit 0
          fi

          npm version patch --no-git-tag-version
          git add package.json

          git commit -m "chore: update WhatsApp Web version and release"
          git pull --rebase origin main
          git push origin main

          npm publish --access public
